# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aria/Desktop/All/University/Classes/AP/Projects

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aria/Desktop/All/University/Classes/AP/Projects

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aria/Desktop/All/University/Classes/AP/Projects/CMakeFiles /home/aria/Desktop/All/University/Classes/AP/Projects/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aria/Desktop/All/University/Classes/AP/Projects/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ChessGame

# Build rule for target.
ChessGame: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ChessGame
.PHONY : ChessGame

# fast build rule for target.
ChessGame/fast:
	$(MAKE) -f CMakeFiles/ChessGame.dir/build.make CMakeFiles/ChessGame.dir/build
.PHONY : ChessGame/fast

src/Chess.o: src/Chess.cpp.o

.PHONY : src/Chess.o

# target to build an object file
src/Chess.cpp.o:
	$(MAKE) -f CMakeFiles/ChessGame.dir/build.make CMakeFiles/ChessGame.dir/src/Chess.cpp.o
.PHONY : src/Chess.cpp.o

src/Chess.i: src/Chess.cpp.i

.PHONY : src/Chess.i

# target to preprocess a source file
src/Chess.cpp.i:
	$(MAKE) -f CMakeFiles/ChessGame.dir/build.make CMakeFiles/ChessGame.dir/src/Chess.cpp.i
.PHONY : src/Chess.cpp.i

src/Chess.s: src/Chess.cpp.s

.PHONY : src/Chess.s

# target to generate assembly for a file
src/Chess.cpp.s:
	$(MAKE) -f CMakeFiles/ChessGame.dir/build.make CMakeFiles/ChessGame.dir/src/Chess.cpp.s
.PHONY : src/Chess.cpp.s

src/Others.o: src/Others.cpp.o

.PHONY : src/Others.o

# target to build an object file
src/Others.cpp.o:
	$(MAKE) -f CMakeFiles/ChessGame.dir/build.make CMakeFiles/ChessGame.dir/src/Others.cpp.o
.PHONY : src/Others.cpp.o

src/Others.i: src/Others.cpp.i

.PHONY : src/Others.i

# target to preprocess a source file
src/Others.cpp.i:
	$(MAKE) -f CMakeFiles/ChessGame.dir/build.make CMakeFiles/ChessGame.dir/src/Others.cpp.i
.PHONY : src/Others.cpp.i

src/Others.s: src/Others.cpp.s

.PHONY : src/Others.s

# target to generate assembly for a file
src/Others.cpp.s:
	$(MAKE) -f CMakeFiles/ChessGame.dir/build.make CMakeFiles/ChessGame.dir/src/Others.cpp.s
.PHONY : src/Others.cpp.s

src/Piece.o: src/Piece.cpp.o

.PHONY : src/Piece.o

# target to build an object file
src/Piece.cpp.o:
	$(MAKE) -f CMakeFiles/ChessGame.dir/build.make CMakeFiles/ChessGame.dir/src/Piece.cpp.o
.PHONY : src/Piece.cpp.o

src/Piece.i: src/Piece.cpp.i

.PHONY : src/Piece.i

# target to preprocess a source file
src/Piece.cpp.i:
	$(MAKE) -f CMakeFiles/ChessGame.dir/build.make CMakeFiles/ChessGame.dir/src/Piece.cpp.i
.PHONY : src/Piece.cpp.i

src/Piece.s: src/Piece.cpp.s

.PHONY : src/Piece.s

# target to generate assembly for a file
src/Piece.cpp.s:
	$(MAKE) -f CMakeFiles/ChessGame.dir/build.make CMakeFiles/ChessGame.dir/src/Piece.cpp.s
.PHONY : src/Piece.cpp.s

src/Setting.o: src/Setting.cpp.o

.PHONY : src/Setting.o

# target to build an object file
src/Setting.cpp.o:
	$(MAKE) -f CMakeFiles/ChessGame.dir/build.make CMakeFiles/ChessGame.dir/src/Setting.cpp.o
.PHONY : src/Setting.cpp.o

src/Setting.i: src/Setting.cpp.i

.PHONY : src/Setting.i

# target to preprocess a source file
src/Setting.cpp.i:
	$(MAKE) -f CMakeFiles/ChessGame.dir/build.make CMakeFiles/ChessGame.dir/src/Setting.cpp.i
.PHONY : src/Setting.cpp.i

src/Setting.s: src/Setting.cpp.s

.PHONY : src/Setting.s

# target to generate assembly for a file
src/Setting.cpp.s:
	$(MAKE) -f CMakeFiles/ChessGame.dir/build.make CMakeFiles/ChessGame.dir/src/Setting.cpp.s
.PHONY : src/Setting.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/ChessGame.dir/build.make CMakeFiles/ChessGame.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/ChessGame.dir/build.make CMakeFiles/ChessGame.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/ChessGame.dir/build.make CMakeFiles/ChessGame.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ChessGame"
	@echo "... src/Chess.o"
	@echo "... src/Chess.i"
	@echo "... src/Chess.s"
	@echo "... src/Others.o"
	@echo "... src/Others.i"
	@echo "... src/Others.s"
	@echo "... src/Piece.o"
	@echo "... src/Piece.i"
	@echo "... src/Piece.s"
	@echo "... src/Setting.o"
	@echo "... src/Setting.i"
	@echo "... src/Setting.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

